# Generated by Django 4.1.1 on 2024-02-06 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                ("username", models.CharField(max_length=255)),
                ("user_profile_pic_url", models.URLField()),
                ("user_joined_date", models.DateField()),
                ("rating", models.IntegerField()),
                ("review_date", models.DateField()),
                ("review_text", models.TextField()),
                ("review_likes", models.IntegerField()),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.product",
                    ),
                ),
            ],
        ),
    ]
